# Generated by Django 3.0.8 on 2021-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-payment_date',),
            },
        ),
    ]
