# Read the Docs configuration file
# Reference: https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

# Build documentation in the docs/ directory
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Python environment setup
python:
  version: 3.11
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra: docs

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Environment variables
env:
  - DJANGO_SETTINGS_MODULE=tests.settings

# Format of the docs
formats:
  - pdf
  - epub

# Search settings
search:
  ranking:
    weights:
      title: 10
      headings: 5
      content: 1
    ignore:
      - /search/
      - /admin/

# Redirect older docs
redirects:
  docs: https://django-paystack.readthedocs.io/

# Subprojects (if any)
# subprojects: []

# Notifications
notifications:
  email:
    on_failure: ""
