# Generated by Django 5.2.8 on 2025-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('risk_action', models.CharField(default='default', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('send_invoices', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('customer_code', models.CharField(db_index=True, max_length=255)),
                ('plan_code', models.CharField(db_index=True, max_length=255)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('non-renewing', 'Non-Renewing'), ('attention', 'Attention'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, max_length=20)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('email_token', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('otp', 'OTP'), ('queued', 'Queued')], db_index=True, max_length=20)),
                ('recipient_code', models.CharField(db_index=True, max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.BigIntegerField(help_text='Amount in kobo')),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization_url', models.URLField(blank=True, null=True)),
                ('access_code', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fees', models.BigIntegerField(blank=True, null=True)),
                ('fees_split', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='djpaystack__referen_6b5154_idx'), models.Index(fields=['status'], name='djpaystack__status_b27769_idx'), models.Index(fields=['customer_email'], name='djpaystack__custome_8afa17_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaystackWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'processed'], name='djpaystack__event_t_3d96a9_idx')],
            },
        ),
    ]
