# Generated by Django 6.0.2 on 2026-02-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djpaystack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paystacktransaction',
            name='djpaystack__referen_6b5154_idx',
        ),
        migrations.RemoveIndex(
            model_name='paystacktransaction',
            name='djpaystack__status_b27769_idx',
        ),
    ]
