# Generated by Django 6.0.2 on 2026-06-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpaystack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paystacktransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("reversed", "Reversed"),
                    ("otp", "OTP"),
                    ("queued", "Queued"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
